name: Test coverage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
          cache: maven

      - name: Build maven
        run: mvn -B package --file pom.xml
        env:
          PG_HOST: ${{secrets.DB_HOST}}
